### ISSUE TITLE
Todo: Game JSON

### ISSUE THREAD

**Issue by metalfoxdev** [Team-Gr1d/gr1d#16]
Work out a way of having game list JSON in a seperate file to declutter the html. Can't access a json file but could make a js file and insert the game list as a var

**Comment by WillGr-dev** [comment]
We should be able to access the json. Will have a look and try update

**Comment by YourSeriousDev** [comment]
Json file added by @WillGr-dev  but not yet implemented

**Comment by YourSeriousDev** [comment]
Implemented json file
